trigger:
  - main

pr: none

pool:
  name: self-hosted-pool

variables:
  azureServiceConnection: 'sc-obs-azure-rg'
  resourceGroupName: 'rg-observability-lab12-standalone'
  acrName: 'obsacrc830a3'
  imageName: 'obsapp-v3'
  aciName: 'obsapp-v3-aci'
  aciDnsName: 'obsapp-francesco-devops'
  location: 'westeurope'
  containerPort: '8000'

stages:
- stage: BuildAndDeploy
  displayName: Build, Push and Deploy
  jobs:
  - job: BuildPushDeploy
    displayName: Build image, push to ACR, deploy to ACI
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Build image, push to ACR and deploy to ACI
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $ErrorActionPreference = "Stop"

          Write-Host "Verifica subscription attiva"
          az account show

          Write-Host "Login ad ACR"
          az acr login --name $(acrName)

          $IMAGE_TAG = "$(Build.BuildId)"
          $FULL_IMAGE_NAME = "$(acrName).azurecr.io/$(imageName):$IMAGE_TAG"

          # 🔥 DNS dinamico (FIX ERRORE)
          $DNS_NAME = "$(aciDnsName)-$IMAGE_TAG"

          Write-Host "Build immagine $FULL_IMAGE_NAME"
          docker build -t $FULL_IMAGE_NAME .

          Write-Host "Push immagine $FULL_IMAGE_NAME"
          docker push $FULL_IMAGE_NAME

          Write-Host "Recupero credenziali ACR"
          $ACR_USER = az acr credential show --name $(acrName) --query username -o tsv
          $ACR_PASS = az acr credential show --name $(acrName) --query "passwords[0].value" -o tsv

          Write-Host "Elimino eventuale container precedente"
          az container delete `
            --resource-group $(resourceGroupName) `
            --name $(aciName) `
            --yes

          Write-Host "Creo nuovo container su ACI"
          az container create --resource-group $(resourceGroupName) --name $(aciName) --image $FULL_IMAGE_NAME --cpu 1 --memory 1.5 --ports $(containerPort) --ip-address Public --dns-name-label $DNS_NAME --location $(location) --registry-login-server "$(acrName).azurecr.io" --registry-username $ACR_USER --registry-password $ACR_PASS --environment-variables PORT=$(containerPort) --os-type Linux

          Write-Host "Recupero FQDN"
          $FQDN = az container show `
            --resource-group $(resourceGroupName) `
            --name $(aciName) `
            --query ipAddress.fqdn `
            -o tsv

          Write-Host "Applicazione disponibile su: http://$FQDN:$(containerPort)"